
spring:
  application:
    name: transfer-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

server:
  port: 8082
springdoc:
  swagger-ui:
